version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-tdd-container
    build: .
    image: api-tdd-image
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/api-tdd/dist
    ports:
      - "5050:5050"
    links:
      - mongo